/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class string_pub_jni_test_TestJni */

#ifndef _Included_string_pub_jni_test_TestJni
#define _Included_string_pub_jni_test_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     string_pub_jni_test_TestJni
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_string_pub_jni_test_TestJni_init
  (JNIEnv *, jobject);

/*
 * Class:     string_pub_jni_test_TestJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_string_pub_jni_test_TestJni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     string_pub_jni_test_TestJni
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_string_pub_jni_test_TestJni_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
